<?php
// =========================================================
// LISTA GLOBAL DE CARRERAS (includes/carreras_globales.php)
// ---------------------------------------------------------
// Nombres de carreras universitarias reconocidas a nivel
// mundial, con ortografía correcta (tildes y ñ). Se usan
// como sugerencias en el formulario de carreras y como
// referencia de validación.
// Devuelve un arreglo indexado de nombres.
// =========================================================
return [
    // === Ingenierías ===
    'Ingeniería de Sistemas',
    'Ingeniería de Sistemas Computacionales',
    'Ingeniería en Sistemas de Información',
    'Ingeniería de Software',
    'Ingeniería en Informática',
    'Ingeniería en Computación',
    'Ingeniería en Telecomunicaciones',
    'Ingeniería en Redes y Telecomunicaciones',
    'Ingeniería en Telemática',
    'Ingeniería en Tecnologías de la Información',
    'Ingeniería en Ciencia de Datos',
    'Ingeniería en Inteligencia Artificial',
    'Ingeniería en Seguridad de la Información',
    'Ingeniería en Mecatrónica',
    'Ingeniería Electrónica',
    'Ingeniería Eléctrica',
    'Ingeniería Mecánica',
    'Ingeniería Civil',
    'Ingeniería Industrial',
    'Ingeniería Química',
    'Ingeniería Ambiental',
    'Ingeniería Agronómica',
    'Ingeniería Agrónoma',
    'Ingeniería Forestal',
    'Ingeniería Geológica',
    'Ingeniería Petrolera',
    'Ingeniería Minera',
    'Ingeniería en Alimentos',
    'Ingeniería de Alimentos',
    'Ingeniería Biomédica',
    'Ingeniería en Energías Renovables',
    'Ingeniería en Producción',
    'Ingeniería en Automatización',
    'Ingeniería Aeronáutica',
    'Ingeniería Naval',
    'Ingeniería en Diseño Industrial',
    'Ingeniería Topográfica',
    'Ingeniería en Nanotecnología',
    'Ingeniería en Materiales',

    // === Arquitectura y Diseño ===
    'Arquitectura',
    'Arquitectura y Diseño de Interiores',
    'Diseño Gráfico',
    'Diseño Industrial',
    'Diseño de Interiores',
    'Diseño de Modas',
    'Diseño de Comunicación Visual',
    'Bellas Artes',
    'Artes Visuales',
    'Artes Plásticas',
    'Artes Escénicas',
    'Cine y Audiovisuales',
    'Teatro',
    'Fotografía',
    'Música',
    'Audiovisuales y Multimedia',

    // === Salud ===
    'Medicina',
    'Medicina General',
    'Enfermería',
    'Odontología',
    'Farmacia',
    'Farmacia y Bioquímica',
    'Nutrición y Dietética',
    'Fisioterapia',
    'Kinesiología',
    'Terapia Ocupacional',
    'Fonoaudiología',
    'Obstetricia',
    'Instrumentación Quirúrgica',
    'Tecnología Médica',
    'Bioquímica',
    'Biología',
    'Química Farmacéutica',
    'Salud Pública',
    'Psicología',
    'Psicología Clínica',
    'Psiquiatría',
    'Medicina Veterinaria',
    'Veterinaria',

    // === Derecho y Ciencias Sociales ===
    'Derecho',
    'Derecho y Ciencias Políticas',
    'Criminología',
    'Ciencias Políticas',
    'Relaciones Internacionales',
    'Sociología',
    'Antropología',
    'Arqueología',
    'Historia',
    'Filosofía',
    'Lingüística',
    'Trabajo Social',
    'Desarrollo Social',
    'Comunicación Social',
    'Periodismo',
    'Comunicación Audiovisual',
    'Marketing',
    'Publicidad',

    // === Economía y Administración ===
    'Administración',
    'Administración de Empresas',
    'Administración Pública',
    'Contaduría Pública',
    'Contabilidad',
    'Auditoría',
    'Economía',
    'Finanzas',
    'Finanzas y Banca',
    'Gestión Empresarial',
    'Gestión de Recursos Humanos',
    'Gestión de Proyectos',
    'Logística y Transporte',
    'Comercio Internacional',
    'Negocios Internacionales',
    'Administración de Turismo',
    'Turismo',
    'Hotelería y Turismo',
    'Gastronomía',
    'Ciencias Empresariales',

    // === Educación y Humanidades ===
    'Educación',
    'Educación Inicial',
    'Educación Parvularia',
    'Educación Primaria',
    'Educación Secundaria',
    'Educación Especial',
    'Pedagogía',
    'Pedagogía en Educación Básica',
    'Pedagogía en Educación Media',
    'Licenciatura en Educación',
    'Psicopedagogía',
    'Ciencias de la Educación',
    'Educación Física',
    'Idiomas',
    'Lenguas Extranjeras',
    'Lengua y Literatura',
    'Traducción e Interpretación',
    'Enseñanza de Idiomas',
    'Música (Licenciatura)',
    'Teología',

    // === Ciencias Exactas y Naturales ===
    'Matemáticas',
    'Matemática Aplicada',
    'Estadística',
    'Física',
    'Química',
    'Ciencias Naturales',
    'Geología',
    'Meteorología',
    'Astronomía',
    'Ciencias de la Computación',
    'Ciencia de Datos',
    'Bioinformática',
    'Física Médica',

    // === Tecnología aplicada (ingenierías/tecnicaturas reconocidas) ===
    'Sistemas Informáticos',
    'Análisis de Sistemas',
    'Desarrollo de Software',
    'Programación de Sistemas',
    'Seguridad Informática',
    'Ciberseguridad',
    'Redes Informáticas',
    'Soporte de Tecnologías de la Información',
    'Tecnología en Sistemas',
    'Tecnología en Informática',
    'Tecnología en Desarrollo de Software',
    'Tecnología en Administración de Redes',
    'Tecnología en Gestión de Bases de Datos',
    'Tecnología en Electrónica',
    'Tecnología en Mecatrónica',
    'Tecnología en Telecomunicaciones',

    // === Agropecuarias ===
    'Ingeniería Agronómica',
    'Agronomía',
    'Zootecnia',
    'Medicina Veterinaria y Zootecnia',
    'Ciencias Agropecuarias',
    'Gestión Ambiental',

    // === Otras carreras reconocidas a nivel mundial ===
    'Ciencias Actuariales',
    'Ciencias Ambientales',
    'Ciencias del Mar',
    'Ciencias Militares',
    'Ciencias Policiales',
    'Ciencias de la Comunicación',
    'Ciencias de la Cultura Física y Deporte',
    'Ciencias de la Actividad Física y del Deporte',
    'Licenciatura en Mercadotecnia',
    'Licenciatura en Contaduría Pública',
    'Economía Internacional',
    'Administración de Negocios Internacionales',
    'Administración Bancaria',
    'Administración Tributaria',
    'Gestión de Negocios Gastronómicos',
    'Ingeniería Comercial',
    'Ingeniería en Marketing',
    'Ingeniería en Finanzas',
    'Ingeniería en Gestión de Proyectos',
    'Ingeniería en Comercio Exterior',
    'Ingeniería Industrial Administrativa',
    'Ingeniería Electrónica y de Telecomunicaciones',
    'Ingeniería en Bioinformática',
    'Ingeniería en Robótica',
    'Ingeniería en Videojuegos',
    'Desarrollo de Videojuegos',
    'Animación Digital',
    'Diseño de Videojuegos',
    'Diseño UX y UI',
    'Diseño de Experiencia de Usuario',
    'Producción Multimedia',
    'Producción de Cine y Televisión',
    'Dirección de Cine',
    'Danza',
    'Musicología',
    'Historia del Arte',
    'Conservación y Restauración de Bienes Culturales',
    'Educación Artística',
    'Traducción y Comunicación Multilingüe',
    'Traducción e Interpretación en Lengua de Señas',
    'Fonoaudiología y Terapia del Lenguaje',
    'Terapia del Lenguaje',
    'Cardiología',
    'Cirugía',
    'Pediatría',
    'Ginecología y Obstetricia',
    'Anestesiología',
    'Radiología e Imagenología',
    'Laboratorio Clínico',
    'Emergencias Médicas',
    'Salud Ocupacional',
    'Seguridad y Salud en el Trabajo',
    'Higiene y Seguridad Industrial',
    'Energías Alternativas',
    'Energía y Medio Ambiente',
    'Nanotecnología',
    'Biotecnología',
    'Bioquímica y Farmacia',
    'Química Industrial',
    'Química Analítica',
    'Astrofísica',
    'Cosmología',
    'Oceanografía',
    'Geomática',
    'Cartografía',
    'Sistemas de Información Geográfica',
    'Ciencias de Datos',
    'Analítica de Datos',
    'Inteligencia Artificial',
    'Machine Learning',
    'Computación Cuántica',
    'Ciberseguridad y Hacking Ético',
    'Seguridad de Redes',
    'Administración de Sistemas',
    'Ingeniería de Nubes',
    'Computación en la Nube',
    'Ingeniería en Ciberseguridad',
    'Tecnología en Seguridad Informática',
    'Optometría',
    'Podología',
    'Quiropraxia',
    'Gerontología',
    'Trabajo Internacional Humanitario',
    'Criminología y Criminalística',
    'Peritaje Judicial',
    'Investigación Criminal',
    'Ciencias Forenses',
    'Periodismo Digital',
    'Comunicación Organizacional',
    'Relaciones Públicas',
    'Publicidad y Marketing',
    'Comercialización',
    'Logística Internacional',
    'Comercio Electrónico',
    'Administración de Hoteles',
    'Administración de Restaurantes',
    'Enología',
    'Museología',
    'Bibliotecología',
    'Archivología',
    'Gobierno y Administración Pública',
    'Políticas Públicas',
    'Estudios Internacionales',
    'Diplomacia',
    'Derecho Ambiental',
    'Derecho Penal',
    'Derecho Tributario',
    'Derecho Laboral',
    'Derecho Empresarial',
    'Derecho Notarial',
    'Derecho de Familia',
    'Enseñanza de la Matemática',
    'Enseñanza de las Ciencias',
    'Didáctica',
    'Currículo y Evaluación Educativa',
    'Orientación Educativa',
    'Gestión Educativa',
    'Psicología Educativa',
    'Psicología Organizacional',
    'Psicología Social',
    'Psicología del Deporte',
    'Medicina Alternativa',
    'Terapia Floral',
    'Acupuntura',
    'Parto Humanizado',
    'Sanidad Animal',
    'Producción Animal',
    'Producción Agrícola',
    'Horticultura',
    'Enóloga',
    'Apicultura',
    'Pesca y Acuicultura',
];