<?php
// =========================================================
// LISTA GLOBAL DE CARRERAS (includes/carreras_globales.php)
// ---------------------------------------------------------
// Nombres de carreras universitarias reconocidas a nivel
// mundial (en español, sin tildes, para mantener el estilo
// del resto del sistema). Se usan como sugerencias en el
// formulario de carreras y como referencia de validación.
// Devuelve un arreglo indexado de nombres.
// =========================================================
return [
    // === Ingenierías ===
    'Ingenieria de Sistemas',
    'Ingenieria de Sistemas Computacionales',
    'Ingenieria en Sistemas de Informacion',
    'Ingenieria de Software',
    'Ingenieria en Informatica',
    'Ingenieria en Computacion',
    'Ingenieria en Telecomunicaciones',
    'Ingenieria en Redes y Telecomunicaciones',
    'Ingenieria en Telematica',
    'Ingenieria en Tecnologias de la Informacion',
    'Ingenieria en Ciencia de Datos',
    'Ingenieria en Inteligencia Artificial',
    'Ingenieria en Seguridad de la Informacion',
    'Ingenieria en Mecatronica',
    'Ingenieria Electronica',
    'Ingenieria Electrica',
    'Ingenieria Mecanica',
    'Ingenieria Civil',
    'Ingenieria Industrial',
    'Ingenieria Quimica',
    'Ingenieria Ambiental',
    'Ingenieria Agronomica',
    'Ingenieria Agronoma',
    'Ingenieria Forestal',
    'Ingenieria Geologica',
    'Ingenieria Petrolera',
    'Ingenieria Minera',
    'Ingenieria en Alimentos',
    'Ingenieria de Alimentos',
    'Ingenieria Biomedica',
    'Ingenieria en Energias Renovables',
    'Ingenieria en Produccion',
    'Ingenieria en Automatizacion',
    'Ingenieria Aeronautica',
    'Ingenieria Naval',
    'Ingenieria en Diseno Industrial',
    'Ingenieria Topografica',
    'Ingenieria en Nanotecnologia',
    'Ingenieria en Materiales',

    // === Arquitectura y Diseño ===
    'Arquitectura',
    'Arquitectura y Diseno de Interiores',
    'Diseno Grafico',
    'Diseno Industrial',
    'Diseno de Interiores',
    'Diseno de Modas',
    'Diseno de Comunicacion Visual',
    'Bellas Artes',
    'Artes Visuales',
    'Artes Plasticas',
    'Artes Escenicas',
    'Cine y Audiovisuales',
    'Teatro',
    'Fotografia',
    'Musica',
    'Audiovisuales y Multimedia',

    // === Salud ===
    'Medicina',
    'Medicina General',
    'Enfermeria',
    'Odontologia',
    'Farmacia',
    'Farmacia y Bioquimica',
    'Nutricion y Dietetica',
    'Fisioterapia',
    'Kinesiologia',
    'Terapia Ocupacional',
    'Fonoaudiologia',
    'Obstetricia',
    'Instrumentacion Quirurgica',
    'Tecnologia Medica',
    'Bioquimica',
    'Biologia',
    'Quimica Farmaceutica',
    'Salud Publica',
    'Psicologia',
    'Psicologia Clinica',
    'Psiquiatria',
    'Medicina Veterinaria',
    'Veterinaria',

    // === Derecho y Ciencias Sociales ===
    'Derecho',
    'Derecho y Ciencias Politicas',
    'Criminologia',
    'Ciencias Politicas',
    'Relaciones Internacionales',
    'Sociologia',
    'Antropologia',
    'Arqueologia',
    'Historia',
    'Filosofia',
    'Linguistica',
    'Trabajo Social',
    'Desarrollo Social',
    'Comunicacion Social',
    'Periodismo',
    'Comunicacion Audiovisual',
    'Marketing',
    'Publicidad',

    // === Economía y Administración ===
    'Administracion',
    'Administracion de Empresas',
    'Administracion Publica',
    'Contaduria Publica',
    'Contabilidad',
    'Auditoria',
    'Economia',
    'Finanzas',
    'Finanzas y Banca',
    'Gestion Empresarial',
    'Gestion de Recursos Humanos',
    'Gestion de Proyectos',
    'Logistica y Transporte',
    'Comercio Internacional',
    'Negocios Internacionales',
    'Administracion de Turismo',
    'Turismo',
    'Hoteleria y Turismo',
    'Gastronomia',
    'Ciencias Empresariales',

    // === Educación y Humanidades ===
    'Educacion',
    'Educacion Inicial',
    'Educacion Parvularia',
    'Educacion Primaria',
    'Educacion Secundaria',
    'Educacion Especial',
    'Pedagogia',
    'Pedagogia en Educacion Basica',
    'Pedagogia en Educacion Media',
    'Licenciatura en Educacion',
    'Psicopedagogia',
    'Ciencias de la Educacion',
    'Educacion Fisica',
    'Idiomas',
    'Lenguas Extranjeras',
    'Lengua y Literatura',
    'Traduccion e Interpretacion',
    'Ensenanza de Idiomas',
    'Musica (Licenciatura)',
    'Teologia',

    // === Ciencias Exactas y Naturales ===
    'Matematicas',
    'Matematica Aplicada',
    'Estadistica',
    'Fisica',
    'Quimica',
    'Ciencias Naturales',
    'Geologia',
    'Meteorologia',
    'Astronomia',
    'Ciencias de la Computacion',
    'Ciencia de Datos',
    'Bioinformatica',
    'Fisica Medica',

    // === Tecnología aplicada (ingenierías/tecnicaturas reconocidas) ===
    'Sistemas Informaticos',
    'Analisis de Sistemas',
    'Desarrollo de Software',
    'Programacion de Sistemas',
    'Seguridad Informatica',
    'Ciberseguridad',
    'Redes Informaticas',
    'Soporte de Tecnologias de la Informacion',
    'Tecnologia en Sistemas',
    'Tecnologia en Informatica',
    'Tecnologia en Desarrollo de Software',
    'Tecnologia en Administracion de Redes',
    'Tecnologia en Gestion de Bases de Datos',
    'Tecnologia en Electronica',
    'Tecnologia en Mecatronica',
    'Tecnologia en Telecomunicaciones',

    // === Agropecuarias ===
    'Ingenieria Agronomica',
    'Agronomia',
    'Zootecnia',
    'Medicina Veterinaria y Zootecnia',
    'Ciencias Agropecuarias',
    'Gestion Ambiental',

    // === Otras carreras reconocidas a nivel mundial ===
    'Ciencias Actuariales',
    'Ciencias Ambientales',
    'Ciencias del Mar',
    'Ciencias Militares',
    'Ciencias Policiales',
    'Ciencias de la Comunicacion',
    'Ciencias de la Cultura Fisica y Deporte',
    'Ciencias de la Actividad Fisica y del Deporte',
    'Licenciatura en Mercadotecnia',
    'Licenciatura en Contaduria Pública',
    'Economia Internacional',
    'Administracion de Negocios Internacionales',
    'Administracion Bancaria',
    'Administracion Tributaria',
    'Gestion de Negocios Gastronomicos',
    'Ingenieria Comercial',
    'Ingenieria en Marketing',
    'Ingenieria en Finanzas',
    'Ingenieria en Gestion de Proyectos',
    'Ingenieria en Comercio Exterior',
    'Ingenieria Industrial Administrativa',
    'Ingenieria Electronica y de Telecomunicaciones',
    'Ingenieria en Bioinformatica',
    'Ingenieria en Robotica',
    'Ingenieria en Videojuegos',
    'Desarrollo de Videojuegos',
    'Animacion Digital',
    'Diseno de Videojuegos',
    'Diseno UX y UI',
    'Diseno de Experiencia de Usuario',
    'Produccion Multimedia',
    'Produccion de Cine y Television',
    'Direccion de Cine',
    'Danza',
    'Musicologia',
    'Historia del Arte',
    'Conservacion y Restauracion de Bienes Culturales',
    'Educacion Artistica',
    'Traduccion y Comunicacion Multilingue',
    'Traduccion e Interpretacion en Lengua de Senas',
    'Fonoaudiologia y Terapia del Lenguaje',
    'Terapia del Lenguaje',
    'Cardiologia',
    'Cirugia',
    'Pediatria',
    'Ginecologia y Obstetricia',
    'Anestesiologia',
    'Radiologia e Imagenologia',
    'Laboratorio Clinico',
    'Emergencias Medicas',
    'Salud Ocupacional',
    'Seguridad y Salud en el Trabajo',
    'Higiene y Seguridad Industrial',
    'Energias Alternativas',
    'Energia y Medio Ambiente',
    'Nanotecnologia',
    'Biotecnologia',
    'Bioquimica y Farmacia',
    'Quimica Industrial',
    'Quimica Analitica',
    'Astrofisica',
    'Cosmologia',
    'Oceanografia',
    'Geomatica',
    'Cartografia',
    'Sistemas de Informacion Geografica',
    'Ciencias de Datos',
    'Analitica de Datos',
    'Inteligencia Artificial',
    'Machine Learning',
    'Computacion Cuantica',
    'Ciberseguridad y Hacking Etico',
    'Seguridad de Redes',
    'Administracion de Sistemas',
    'Ingenieria de Nubes',
    'Computacion en la Nube',
    'Ingenieria en Ciberseguridad',
    'Tecnologia en Seguridad Informatica',
    'Optometria',
    'Podologia',
    'Quiropraticia',
    'Gerontologia',
    'Trabajo Internacional Humanitario',
    'Criminologia y Criminalistica',
    'Peritaje Judicial',
    'Investigacion Criminal',
    'Ciencias Forenses',
    'Periodismo Digital',
    'Comunicacion Organizacional',
    'Relaciones Publicas',
    'Publicidad y Marketing',
    'Comercializacion',
    'Logistica Internacional',
    'Comercio Electronico',
    'Administracion de Hoteles',
    'Administracion de Restaurantes',
    'Enologia',
    'Museologia',
    'Bibliotecologia',
    'Archivologia',
    'Gobierno y Administracion Publica',
    'Politicas Publicas',
    'Estudios Internacionales',
    'Diplomacia',
    'Derecho Ambiental',
    'Derecho Penal',
    'Derecho Tributario',
    'Derecho Laboral',
    'Derecho Empresarial',
    'Derecho Notarial',
    'Derecho de Familia',
    'Ensenanza de la Matematica',
    'Ensenanza de las Ciencias',
    'Didactica',
    'Curriculo y Evaluacion Educativa',
    'Orientacion Educativa',
    'Gestion Educativa',
    'Psicologia Educativa',
    'Psicologia Organizacional',
    'Psicologia Social',
    'Psicologia del Deporte',
    'Medicina Alternativa',
    'Terapia Floral',
    'Acupuntura',
    'Parto Humanizado',
    'Sanidad Animal',
    'Produccion Animal',
    'Produccion Agricola',
    'Horticultura',
    'Enologa',
    'Apicultura',
    'Pesca y Acuicultura',
];